project:
  type: website

website:
  title: "Meshal alotaibi"
  favicon: "images/1.jpg"
  page-footer:
    center: |
      [Contact Meshal alotaibi](Meshal.alotaibie1@gmail.com)
    left: |
      Made with [Meshal alotaibi](https://github.com/meshalalotaibie)
    right: |
      [Github Code Repo](https://github.com/meshalalotaibie/personal_portfolio_meshalalotaibie.git)
    background: "#e3275a"
    
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
        
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      light: cyborg
      dark: [lux, theme_dark_custom.scss]
    highlight-style: github
editor: visual
